In [3]:
#NumPy is a python library 
import numpy as np # this is main library and we need to import it first.

#create a array using NumPy
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#check the type of an obejct 
type(arr)

In [3]:
#convert a list into numpy 
list1 = [12,56,23,45,78]
arr1 = np.array(list1)
arr1

array([12, 56, 23, 45, 78])

In [4]:
#Memory address of an array object
arr1.data

In [6]:
# to check the dimension of array 
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
d.ndim

3

In [33]:
# to change the dimension 
a = np.array([1,2,3,4],ndmin=3)
print(a)
print('shape of array:',a.shape)

[[[1 2 3 4]]]
shape of array: (1, 1, 4)


In [10]:
#Datatype of array
d.dtype    # Convert Integer Array to FLOAT
d.astype(float)

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [12]:
# Datatype of object
d.dtype

dtype('int32')

In [15]:
# Length of array
len(arr1)

5

In [16]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Generate numbers between 0 to 100 with a space of 4
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [20]:
# Generate numbers between 10 to 100 with a space of 5 in descending order
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [25]:
#Shape of Array
arr2 = np.arange(1,20)
print(arr2)
arr2.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(19,)

In [26]:
# Generate an array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
# Repeat 10 ten times in an array
np.repeat(10,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [28]:
# Array of 10
np.full(5,10)

array([10, 10, 10, 10, 10])

In [30]:
# Generate array of even numbers
arr3 = np.arange(1,20)
arr3[arr3%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# Create an array of random values
np.random.random(4)

array([0.65025653, 0.48655778, 0.78547999, 0.06895809])

In [34]:
# Generate an array of Random Integer numbers
np.random.randint(0,100,10)

array([70, 99, 74, 54, 44, 29, 88, 47, 52, 44])

In [37]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(12)
np.random.randint(0,50,5)

array([11, 27,  6, 49,  2])

In [40]:
# Generate array of Random float numbers
f = np.random.uniform(5,10, size=(10))
f

array([9.26367771, 5.01129617, 7.60613014, 7.76018817, 7.42688707,
       8.84067077, 5.80358377, 8.82280225, 5.10404899, 5.67605089])

In [41]:
# Extract Integer part
np.floor(f)

array([9., 5., 7., 7., 7., 8., 5., 8., 5., 5.])

In [42]:
# Truncate decimal part
np.trunc(f)

array([9., 5., 7., 7., 7., 8., 5., 8., 5., 5.])

In [43]:
# Convert Float Array to Integer array
f.astype(int)

array([9, 5, 7, 7, 7, 8, 5, 8, 5, 5])

In [44]:
# Random numbers from standard Normal distribution 
b2 =np.random.randn(10)
b2

array([-0.34947094, -0.70541676, -0.34018626,  2.02729871, -0.58108011,
        0.87313484,  0.91056528,  1.04764561, -1.18963857, -1.24056205])

In [45]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
 print(index, value)

(0,) 12
(1,) 56
(2,) 23
(3,) 45
(4,) 78


**Operations on array**

In [47]:
# Sum of all elements in an array
arr.sum()

15

In [49]:
# Cumulative Sum
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [50]:
# Find Minimum number in an array
arr.min()

1

In [51]:
# Find MAX number in an array
arr.max()

5

In [52]:
# Find INDEX of Minimum number in an array
arr.argmin()

0

In [54]:
# Find INDEX of MAX number in an array
arr.argmax()

4

In [55]:
# Find mean of all numbers in an array
arr.mean()

3.0

In [56]:
# Find median of all numbers present in arr2
np.median(arr)

3.0

In [57]:
# Variance
np.var(arr)

2.0

In [58]:
# Standard deviation
np.std(arr)

1.4142135623730951

In [59]:
# Calculating percentiles
np.percentile(arr,70)

3.8

In [61]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(d):
 print(index, value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6


In [62]:
# reading element in an array 
a = np.array([7,5,3,9,0,2])
print(a)
# Access first element of the array
a[0]

[7 5 3 9 0 2]


7

In [63]:
#slicing of an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[4:])

[5 6 7 8 9]


In [ ]:
# negative slicing
print(arr[-3:-1])

In [64]:
#slicing of an array in 2 steps 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [4]:
# sorting in Assending order (By-default)
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)
print(y)

[1 3 3 4 5 7 8 9]


In [5]:
# To sorting in Desending order
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)[::-1]
print(y)

[9 8 7 5 4 3 3 1]


In [6]:
x=np.array([1,4,5,7,3,8,3,9])
y=np.argsort(x)
print(y)

[0 4 6 1 2 3 5 7]
