In [5]:
import numpy as np
from numpy import random
#generate from binomial distribution
x = random.binomial(n=10, p=0.5, size=10)
print(x)

[4 5 3 5 2 5 4 3 5 7]


In [6]:
#generate from poission distribution
y = random.poisson(lam=2, size=10)
print(y)

[2 1 1 0 2 0 5 0 0 1]


In [7]:
#generate from uniform distribution
z = random.uniform(size=(1,3))
print(z)

[[0.50600298 0.4028009  0.99040177]]


In [8]:
# logistic distribution
x = random.logistic(loc=1, scale=2, size=(2, 3))
print(x)

[[ 1.28381902 -4.75830513  0.1400103 ]
 [-5.07215957  0.14052933  4.60249851]]


In [9]:
#generte random number from multinomial distribution
x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
print(x)

[0 1 1 1 1 2]


In [ ]:
# exponential distribution
x = random.exponential(scale=2, size=(2, 3))
print(x)

In [10]:
#chi-square distribution
x = random.chisquare(df=2, size=(2, 3))
print(x)

[[1.49548157 3.79187826 2.6091746 ]
 [0.84212916 3.78607924 1.1561579 ]]


In [ ]:
#rayleigh distribution
x = random.rayleigh(scale=2, size=(2, 3))
print(x)

In [11]:
#pareto distribution
x = random.pareto(a=2, size=(2, 3))
print(x)

[[0.44723134 0.16987642 1.07561373]
 [0.24383295 0.60178377 0.40388311]]


In [12]:
#reshape
x = random.normal(size=(2, 3))
print(x)
y = random.normal(size=(2, 3))
newx =x.reshape(-1)
print(newx)

[[-0.56901035  2.23886923  1.58269396]
 [-0.94669026  0.18464336 -2.95933385]]
[-0.56901035  2.23886923  1.58269396 -0.94669026  0.18464336 -2.95933385]


In [13]:
#permutation
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[4 2 5 1 3]


In [14]:
#shuffle
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[4 1 3 2 5]


In [15]:
#choice
y= random.choice([3, 5, 7, 9])
print(y)

7
